FROM python:3.10
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_HOME='/usr/local' \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR='/var/cache/pypoetry' \
    PYTHONPATH='/app/src' \
    IN_DOCKER=true
RUN curl -sSL https://install.python-poetry.org | python -
WORKDIR /app/
COPY Makefile .env poetry.lock pyproject.toml /app/
COPY backend/src /app/src/
RUN poetry install --no-root --without dev
CMD ["make", "run-in-docker"]
