FROM python:3.10
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_HOME='/usr/local' \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR='/var/cache/pypoetry' \
    DOTENV_PATH='/app/.env' \
    PYTHONPATH='/app/src'
RUN curl -sSL https://install.python-poetry.org | python -
WORKDIR /app/
COPY backend/poetry.lock backend/pyproject.toml /app/
RUN poetry install --no-root --without dev
COPY .env /app
COPY backend/src /app/src
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "5000"]
